#!/usr/bin/env python3
"""Packs the Amiga Larn tiles (port/amiga/*.png, 8x16, from larn.org /
github.com/primeau/Larn, MIT; primeau's ULarn mode) into web/tiles.png and
writes port/tilemap.h. Copied from ~/Games/larn/port/mktiles.py.

mN = monster N, oN = object N, wN = wall with neighbour bits (2 up, 4 right,
8 down, 16 left). Ularn ids match primeau's except MON_REMAP / OBJ_REMAP.
Checks that every monster and object id in src/data.c has a tile (one set,
no fallback) and prints the coverage. Run from the repo root."""
import re
from pathlib import Path
from PIL import Image

SRC = Path("port/amiga")
PER_ROW = 32
data = Path("src/data.c").read_text(encoding="latin-1")
tab = data[data.index("struct monst monster[]"):]
NMON = len(re.findall(r'^\{\s*"', tab[:tab.index("\n};")], re.M))      # 0..LUCIFER
NOBJ = len(re.findall(r'^#define O\w+\s+\d+', Path("src/itm.h").read_text(), re.M)) + 1  # 0..OPAD
# ULarn art: lemming, bitbug, lama nobe; the stalker and demons as seen with the Eye
MON_REMAP = {1: "m1u", 19: "m19u", 34: "m34u", 39: "m39v", **{i: f"m{i}v" for i in range(57, 66)}}
OBJ_REMAP = {15: 16, 16: 15, 80: 82, 82: 80, **{i: i + 2 for i in range(93, 99)}, 21: "wall"}

names = []


def add(name):
    assert (SRC / f"{name}.png").exists(), f"no tile {name}"
    if name not in names:
        names.append(name)
    return names.index(name)


mon = [add(MON_REMAP.get(i, f"m{i}")) for i in range(NMON)]
obj = []
for i in range(NOBJ):
    r = OBJ_REMAP.get(i, i)
    obj.append(-2 if r == "wall" else add(f"o{r}"))
wall = [add(f"w{m}") for m in range(0, 32, 2)]
player = add("player")
print(f"coverage: monsters {NMON - 1}/{NMON - 1}, objects {NOBJ - 1}/{NOBJ - 1} (100%), {len(names)} tiles")

rows = (len(names) + PER_ROW - 1) // PER_ROW
sheet = Image.new("RGBA", (PER_ROW * 8, rows * 16))
for i, n in enumerate(names):
    t = Image.open(SRC / f"{n}.png").convert("RGBA")
    if t.size != (8, 16):  # o90 (Vorpal Blade) is 13x20 upstream
        t = t.resize((8, 16), Image.NEAREST)
    sheet.paste(t, ((i % PER_ROW) * 8, (i // PER_ROW) * 16))
sheet.save("web/tiles.png")


def arr(a):
    return ",".join(map(str, a))


Path("port/tilemap.h").write_text(f"""/* Generated by port/mktiles.py from the Amiga Larn tiles. Do not edit. */
static const short mon_tile[{len(mon)}] = {{{arr(mon)}}};
/* -2 = wall (wall_tile by neighbours) */
static const short obj_tile[{len(obj)}] = {{{arr(obj)}}};
static const short wall_tile[16] = {{{arr(wall)}}};
#define PLAYER_TILE {player}
""")
